export const navLinks = [
    { label: 'Home', href: '/' },
    { label: 'Explore', href: '/celestial' },
    { label: 'Missions', href: '/missions' },
    { label: 'People', href: '/people' },
    { label: 'Live', href: '/launches' },
] as const

export const categories = [
    {
        label: 'Planets',
        slug: 'planets',
        href: '/celestial?type=PLANET',
        description: 'Rocky worlds & gas giants',
        count: '8 in solar system',
        image: 'https://images.unsplash.com/photo-1639921884918-8d28ab2e39a4?w=600&q=80',
        accent: '#4a90d9',
        type: 'PLANET',
    },
    {
        label: 'Stars',
        slug: 'stars',
        href: '/celestial?type=STAR',
        description: 'From dwarfs to supergiants',
        count: '200B+ in Milky Way',
        image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=600&q=80',
        accent: '#f5a623',
        type: 'STAR',
    },
    {
        label: 'Galaxies',
        slug: 'galaxies',
        href: '/celestial?type=GALAXY',
        description: 'Islands of billions of stars',
        count: '2T+ in observable universe',
        image: 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=600&q=80',
        accent: '#9b59b6',
        type: 'GALAXY',
    },
    {
        label: 'Nebulae',
        slug: 'nebulae',
        href: '/celestial?type=NEBULA',
        description: 'Stellar nurseries & remnants',
        count: 'Thousands catalogued',
        image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=600&q=80',
        accent: '#e74c9f',
        type: 'NEBULA',
    },
    {
        label: 'Black Holes',
        slug: 'black-holes',
        href: '/celestial?type=BLACK_HOLE',
        description: 'Where spacetime breaks down',
        count: 'Millions estimated',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80',
        accent: '#a855f7',
        type: 'BLACK_HOLE',
    },
    {
        label: 'Missions',
        slug: 'missions',
        href: '/missions',
        description: 'Human ventures into the void',
        count: '500+ space missions',
        image: 'https://images.unsplash.com/photo-1516849677043-ef67c9557e16?w=600&q=80',
        accent: '#27ae60',
        type: 'MISSION',
    },
] as const